### ISSUE TITLE
Crear menú oculto

### ISSUE THREAD

**Issue by juanFGR** [PLGRUPO/AnalisisAmbitoJison#11]
Crear menú oculto solo para usuarios que hagan login donde puedan ver la lista de ficheros y usuarios completa

**Comment by alu0100700459** [comment]
Debería haber una opción para hacer log off, ¿no?
Dentro del menú oculto este podría ser bueno tener además de ver la lista de usuarios y los programas de cada uno un botón para cerrar sesión

**Comment by juanFGR** [comment]
debería pero no tengo ni idea de como destruir una session en ruby porque
no es solo salir y entrar o poner la variable a null...sino acceder al
navegador y borrar la sesion porque los navegadores te guardan la sesion
con google y facebook

**Comment by juanFGR** [comment]
de todas formas deja mirarlo a ver, sabes algo de iaa de que les metió en
el control o que pidió de la practica??

**Comment by alu0100700459** [comment]
Ah vale entonces no nos complicamos con eso mejor, que ya está acabado
todo... De IAA no sé nada, la verdad.
